### ISSUE TITLE
Enhance set print area

### ISSUE THREAD

**Issue by johnksv** [perliedman/o-scout#1]
Hi! First of all; Thank you for creating o-scout!
This is a feature request.

Current behaviour:
There are two "modes" for print area: Auto or manual
"Auto" will set an area based on the "size" of your course.
Manual lets you set the clip/coordinates yourself
<img width="304" alt="Screenshot 2022-07-20 at 14 25 59" src="https://user-images.githubusercontent.com/10381866/179981445-f5bf59d7-56f9-4aca-ae7b-2b34be667b6e.png">

I think some more alternatives to set the print area would be nice.
Some ideas could be:
- Ability to set the print area/manual coordinates by "click 'n drag" on map(/click on the map to define the values)
- Ability to select "Whole map" as print area
- In some way visualise the print area vs Paper size

**Comment by perliedman** [comment]
Hi @johnksv!

Nice to see you have found o-scout!

For the first suggestion, there actually already is, but apparently needs some refinement since you did not find it. If you select "Area" from the top toolbar, you can drag the edges of the print area as desired, like below:

![image](https://user-images.githubusercontent.com/1246614/180770907-438ec4e7-aa29-4b7a-b649-76ec9788af95.png)

As for the other two suggestions, I agree, that should be added. I think the ability to make sure the area fits to the desired paper size is really important.

**Comment by perliedman** [comment]
Revisiting this issue, it looks like @wlfrdssn's recent work solved a lot of the remaining issues, and we also have #26 which covers another of the listed use cases, so I'm closing this.
