### ISSUE TITLE
Export course as IOF Data Standard 3.0 XML

### ISSUE THREAD

**Issue by johnksv** [perliedman/o-scout#3]
Feature request:
Add support for exporting course as IOF Data Standard 3.0 XML.
This would allow users to import courses into other software/solutions, like Eventor, Livelox, O-Range, OCAD, etc.

As described here: https://orienteering.sport/iof/it/data-standard-3-0/

IOF data standard on github: https://github.com/international-orienteering-federation/datastandard-v3

Example file of course: https://github.com/international-orienteering-federation/datastandard-v3/blob/master/examples/CourseData_Individual_Step2.xml

**Comment by perliedman** [comment]
Thanks for the suggestions and links! Locally I have a WIP of outputting Purple Pen files, but IOF XML probably makes more sense since it's interoperable with more tools.

Don't know if you already saw it, but you can load Purple Pen events already (although I'm sure a lot of features except the basics are not correctly handled). Loading IOF XML sounds like something I should work on too.

**Comment by perliedman** [comment]
I hacked up a first attempt at this. The produced file at least seems to pass XML schema validation for IOF XML 3.0, and as far as I can tell it at least looks correct. Having said that I don't have easy access to any of the tools you mention, so I haven't tried it with those yet, so there might of course be issues.

Feedback is of course very welcome!
